export { default as Register } from './Register'
export { default as Login } from './Login'
export { default as ConfirmEmail } from './ConfirmEmail'
export { default as ChangePassword } from './ChangePassword'
export { default as ForgotPassword } from './ForgotPassword'
export { default as ResetPassword } from './ResetPassword'
